[package]
name = "wasm-live-handlebars"
version = "0.1.0"
authors = ["Thomas Lacroix <toto.rigolo@free.fr>"]
edition = "2018"

[dependencies]
anyhow = "1"
yew = "0.12.0"
handlebars = "3"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
lazy_static = "1"